const labels = [
	{
		name: "name",
		label: "Tu nombre real",
		officerString: "Nombre",
		type: "text",
		required: true,
		style: "short",
		section: 0,
	},
	{
		name: "age",
		label: "Edad",
		officerString: "Edad",
		type: "number",
		required: true,
		style: "short",
		section: 0,
	},
	{
		name: "characterName",
		label: "Nombre de personaje",
		officerString: "Personaje",
		type: "text",
		required: true,
		style: "short",
		section: 0,
	},
	{
		name: "battlenetID",
		label: "ID de Battle.net",
		officerString: "Bnet",
		type: "text",
		required: true,
		style: "short",
		section: 0,
	},
	{
		name: "email",
		label: "Correo Electronico",
		officerString: "Mail",
		type: "text",
		required: true,
		style: "short",
		section: 0,
	},
	{
		name: "country",
		label: "País de Origen",
		officerString: "País",
		type: "text",
		required: true,
		style: "short",
		section: 0,
	},
	{
		name: "discordUserName",
		label: "Usuario de Discord",
		officerString: "Discord",
		type: "text",
		required: true,
		style: "short",
		section: 0,
	},
	{
		name: "wowArmory",
		label: "Link de tu Armory de WoW",
		officerString: "Armory",
		type: "text",
		required: true,
		style: "large",
		section: 2,
	},
	{
		name: "dateRaiding",
		label: "¿Desde que parche raideas?",
		officerString: "Raideo desde",
		type: "text",
		required: true,
		style: "short",
		section: 0,
	},
	{
		name: "microphoneAvailable",
		label: "¿Cuentas con microfono y puedes hablar?",
		officerString: "Microfono",
		type: "radio",
		required: true,
		style: "short",
		section: 1,
		options: ["Si", "No"],
	},
	{
		name: "netSpeed",
		label: "Velocidad de conexión y latencia",
		type: "text",
		officerString: "Internet",
		required: true,
		style: "short",
		section: 0,
	},
	{
		name: "lastGuild",
		label: "¿De qué Guild vienes?",
		officerString: "Guild de Origen",
		type: "text",
		required: true,
		style: "short",
		section: 0,
	},
	{
		name: "selfAwareness",
		label: "¿Puedes jugar 2 personajes en buen nivel?",
		officerString: "2 personajes",
		type: "radio",
		options: ["Si", "No"],
		required: true,
		style: "short",
		section: 1,
	},

	{
		name: "screenshot",
		label:
			"Toma una captura de pantalla de tu interfaz de WoW mientras raideas e inserta el link (1) revisa que sea válido",
		officerString: "Interfaz",
		type: "text",
		required: true,
		style: "large",
		section: 2,
	},
	{
		name: "POV",
		label: "Si cuentas con un PoV de alguna pelea, copia el enlace",
		officerString: "PoV",
		type: "text",
		required: false,
		style: "large",
		section: 2,
	},
	{
		name: "warcraftLogs",
		label: "Coloca tu enlace de WarcraftLogs",
		officerString: "WarcraftLogs",
		type: "text",
		required: true,
		style: "large",
		section: 2,
	},
	{
		name: "raidExperience",
		label: "¿Qué experiencia tienes en raid, logros ó ranks sobresalientes, guilds a las cuales perteneciste?",
		officerString: "Experiencia",
		type: "textarea",
		required: true,
		style: "large",
		section: 2,
	},
	{
		name: "expertise",
		label: "¿Qué consideras que te hace sobresalir de los demás?",
		officerString: "Habilidades",
		type: "textarea",
		required: true,
		style: "large",
		section: 2,
	},
	{
		name: "applyReason",
		label: "¿Por qué quieres unirte a Unity?",
		officerString: "Razón de aplicar",
		type: "textarea",
		required: true,
		style: "large",
		section: 2,
	},

	{
		name: "lastGuildLeavingReason",
		label: "¿Por qué quieres dejar tu guild actual?",
		officerString: "Razón de dejar su guild",
		type: "textarea",
		required: true,
		style: "large",
		section: 2,
	},
	{
		name: "aboutYourself",
		label: "Háblanos de ti y dinos que puedes aportar a Unity",
		officerString: "Sobre mi",
		type: "textarea",
		required: true,
		style: "large",
		section: 2,
	},
];

export default labels;
