const unityDB = {
	unityData: {
		shadowlands: [],
		battleForAzeroth: {
			tiers: ["nyalotha-the-waking-city", "the-eternal-palace", "crucible-of-storms", "battle-of-dazaralor", "uldir"],
			raids: {
				"nyalotha-the-waking-city": {
					tier: 4,
					raid: [
						{
							data: [
								"2020-01-28T21:35:00.000Z",
								true,
								" https://www.youtube.com/watch?v=ESTst5-O4Lc&feature=youtu.be",
								"7",
								"9",
								"1",
							],
							slug: "wrathion-the-black-emperor",
						},
						{
							slug: "the-prophet-skitra",
							data: ["2020-01-28T22:03:00.000Z", true, "#", "2", "10", "1"],
						},
						{
							data: [
								"2020-01-28T23:59:00.000Z",
								true,
								"https://www.youtube.com/watch?v=jEoCDUs6X-U&feature=youtu.be",
								"15",
								"10",
								"1",
							],
							slug: "maut",
						},
						{
							slug: "shadhar-the-insatiable",
							data: ["2020-01-31T03:31:00.000Z", true, "https://www.youtube.com/watch?v=VcmT8fYleg8", "56", "40", "1"],
						},
						{
							data: ["2020-02-03T03:07:00.000Z", true, "https://www.youtube.com/watch?v=Sdh-ysaveB4", "32", "60", "2"],
							slug: "the-hivemind",
						},
						{
							slug: "dark-inquisitor-xanesh",
							data: ["2020-02-06T05:52:00.000Z", true, "#", "102", "119", "1"],
						},
						{
							data: ["2020-02-10T01:27:00.000Z", true, "#", "41", "37", "1"],
							slug: "vexiona",
						},
						{
							slug: "drestagath",
							data: ["2020-02-14T03:04:00.000Z", true, "#", "74", "125", "1"],
						},
						{
							data: ["2020-02-20T04:31:00.000Z", true, "#", "138", "169", "1"],
							slug: "ra-den-the-despoiled",
						},
						{
							slug: "ilgynoth-corruption-reborn",
							data: ["2020-02-22T04:54:00.000Z", true, "#", "34", "120", "1"],
						},
						{
							slug: "carapace-of-nzoth",
							data: ["2020-02-27T06:10:00.000Z", true, "https://www.youtube.com/watch?v=G24RpgZzy7M", "85", "95", "1"],
						},
						{
							slug: "nzoth-the-corruptor",
							data: [
								"2020-03-16T23:52:00.000Z",
								true,
								"https://www.youtube.com/watch?v=wM6VZXkU1cU",
								"411",
								"105",
								"1",
							],
						},
					],
				},
				"battle-of-dazaralor": {
					tier: 1,
					raid: [
						{
							data: ["2019-01-29T20:13:00.000Z", true, "https://www.youtube.com/watch?v=CO38biMNc9o", "1", "20", "1"],
							slug: "champion-of-the-light",
						},
						{
							slug: "grong",
							data: ["2019-01-30T00:32:00.000Z", true, "https://www.youtube.com/watch?v=9q6M4vOm2Yk", "58", "12", "1"],
						},
						{
							data: ["2019-02-01T02:21:00.000Z", true, "https://www.youtube.com/watch?v=sUfP8KlxcK8", "58", "512", "5"],
							slug: "jadefire-masters",
						},
						{
							slug: "opulence",
							data: ["2019-02-02T02:19:00.000Z", true, "https://www.youtube.com/watch?v=2_J3w_vSltg", "39", "119", "2"],
						},
						{
							data: ["2019-02-05T02:06:00.000Z", true, "https://www.youtube.com/watch?v=VwPTzdOHeqA", "78", "189", "2"],
							slug: "conclave-of-the-chosen",
						},
						{
							slug: "king-rastakhan",
							data: ["2019-02-08T04:50:00.000Z", true, "https://www.youtube.com/watch?v=l6KkKy5_uvo", "53", "212", "2"],
						},
						{
							slug: "high-tinker-mekkatorque",
							data: ["2019-02-11T03:49:00.000Z", true, "https://www.youtube.com/watch?v=Phf-qC6KKrs", "79", "135", "2"],
						},
						{
							slug: "stormwall-blockade",
							data: [
								"2019-02-18T03:31:00.000Z",
								true,
								"https://www.youtube.com/watch?v=HHr0abaHXhw",
								"163",
								"123",
								"2",
							],
						},
						{
							data: [
								"2019-03-20T04:09:00.000Z",
								true,
								"https://www.youtube.com/watch?v=j8f-DTDn7cQ",
								"570",
								"141",
								"1",
							],
							slug: "lady-jaina-proudmoore",
						},
					],
				},
				uldir: {
					raid: [
						{
							slug: "taloc",
							data: ["2018-09-11T19:27:00.000Z", true, "https://www.youtube.com/watch?v=s_5i-NWE5kQ", "1", "12", "1"],
						},
						{
							data: ["2018-09-11T21:20:00.000Z", true, "https://www.youtube.com/watch?v=kPkALND5z4M", "18", "12", "1"],
							slug: "mother",
						},
						{
							data: ["2018-09-14T02:54:00.000Z", true, "https://www.youtube.com/watch?v=F34z2rmojJ4", "60", "102", "3"],
							slug: "zekvoz-herald-of-nzoth",
						},
						{
							data: [
								"2018-09-17T04:59:00.000Z",
								true,
								"https://www.youtube.com/watch?v=BbD0BUm4M8U&feature=youtu.be",
								"45",
								"97",
								"3",
							],
							slug: "vectis",
						},
						{
							data: [
								"2018-09-22T04:27:00.000Z",
								true,
								"https://www.youtube.com/watch?v=qBlo9SqUnRk&feature=youtu.be",
								"170",
								"83",
								"3",
							],
							slug: "fetid-devourer",
						},
						{
							data: [
								"2018-09-24T03:54:00.000Z",
								true,
								"https://www.youtube.com/watch?v=KP10CjNBJf4&t=",
								"62",
								"68",
								"3",
							],
							slug: "zul-reborn",
						},
						{
							data: ["2018-10-02T02:55:00.000Z", true, "", "204", "83", "3"],
							slug: "mythrax-the-unraveler",
						},
						{
							data: ["2018-10-13T05:37:00.000Z", true, "https://www.youtube.com/watch?v=QL07CyEFOZg", "364", "95", "3"],
							slug: "ghuun",
						},
					],
					tier: 0,
				},
				"the-eternal-palace": {
					tier: 3,
					raid: [
						{
							slug: "abyssal-commander-sivara",
							data: ["2019-07-16T21:08:00.000Z", true, "#", "18", "14", "1"],
						},
						{
							slug: "radiance-of-azshara",
							data: ["2019-07-16T22:28:00.000Z", true, "#", "8", "14", "1"],
						},
						{
							data: ["2019-07-17T01:11:00.000Z", true, "#", "8", "17", "1"],
							slug: "blackwater-behemoth",
						},
						{
							slug: "lady-ashvane",
							data: ["2019-07-26T02:04:00.000Z", true, "#", "120", "140", "1"],
						},
						{
							data: ["2019-08-02T01:52:00.000Z", true, "https://www.youtube.com/watch?v=bTwkbzHwdx0", "88", "158", "1"],
							slug: "orgozoa",
						},
						{
							data: [
								"2019-08-08T03:57:00.000Z",
								true,
								"https://www.youtube.com/watch?v=ADsmxuqRwEk&t",
								"122",
								"142",
								"1",
							],
							slug: "the-queens-court",
						},
						{
							data: [
								"2019-08-16T04:38:00.000Z",
								true,
								"https://www.youtube.com/watch?v=0rD-v35BjWU",
								"157",
								"119",
								"1",
							],
							slug: "zaqul",
						},
						{
							slug: "queen-azshara",
							data: [
								"2019-09-09T04:32:00.000Z",
								true,
								"https://www.youtube.com/watch?v=JkaGIzwz7Ps",
								"326",
								"106",
								"1",
							],
						},
					],
				},
				"crucible-of-storms": {
					raid: [
						{
							slug: "the-restless-cabal",
							data: [
								"2019-05-09T04:20:00.000Z",
								true,
								"https://www.youtube.com/watch?v=JJny6f5LmkA",
								"286",
								"108",
								"1",
							],
						},
						{
							data: ["2019-06-07T02:20:00.000Z", true, "https://www.youtube.com/watch?v=TqLJf1iCXWM", "403", "84", "1"],
							slug: "uunat-harbinger-of-the-void",
						},
					],
					tier: 2,
				},
			},
		},
	},
	currentTier: {
		bossCount: 12,
		slug: "nyalotha-the-waking-city",
		expansion: "battleForAzeroth",
		tierNumber: 4,
	},
	guildsRanking: {
		shadowlands: [],
		battleForAzeroth: [
			{
				rankings: [
					{
						id: 9484,
						regionRank: 45,
						name: "Unity",
						realm: "Ragnaros",
						region: "us",
						encountersDefeated: 9,
						rank: 1,
					},
					{
						realm: "Ragnaros",
						regionRank: 132,
						rank: 2,
						region: "us",
						name: "Epic Wipe",
						id: 42826,
						encountersDefeated: 9,
					},
					{
						regionRank: 138,
						rank: 3,
						id: 481128,
						name: "Erased Memories",
						region: "us",
						realm: "Ragnaros",
						encountersDefeated: 9,
					},
					{
						rank: 4,
						name: "Without Elders",
						realm: "Ragnaros",
						regionRank: 162,
						region: "us",
						id: 655391,
						encountersDefeated: 9,
					},
					{
						realm: "Ragnaros",
						name: "HTF",
						regionRank: 202,
						region: "us",
						rank: 5,
						encountersDefeated: 9,
						id: 42886,
					},
				],
				slug: "battle-of-dazaralor",
				raidNumber: 1,
			},
			{
				raidNumber: 4,
				slug: "nyalotha-the-waking-city",
				rankings: [
					{
						id: 9484,
						name: "Unity",
						regionRank: 28,
						region: "us",
						rank: 1,
						encountersDefeated: 12,
						realm: "Ragnaros",
					},
					{
						id: 1039147,
						realm: "Ragnaros",
						encountersDefeated: 12,
						regionRank: 94,
						rank: 2,
						name: "GordoTiburonSi",
						region: "us",
					},
					{
						rank: 3,
						region: "us",
						encountersDefeated: 12,
						regionRank: 102,
						name: "Without Elders",
						id: 655391,
						realm: "Ragnaros",
					},
					{
						encountersDefeated: 12,
						rank: 4,
						id: 42826,
						realm: "Ragnaros",
						regionRank: 114,
						region: "us",
						name: "Epic Wipe",
					},
					{
						encountersDefeated: 12,
						regionRank: 169,
						region: "us",
						rank: 5,
						id: 42886,
						name: "HTF",
						realm: "Ragnaros",
					},
				],
			},
			{
				rankings: [
					{
						name: "Unity",
						rank: 1,
						region: "us",
						id: 9484,
						realm: "Ragnaros",
						regionRank: 56,
						encountersDefeated: 2,
					},
					{
						regionRank: 73,
						name: "Epic Wipe",
						id: 42826,
						encountersDefeated: 1,
						realm: "Ragnaros",
						region: "us",
						rank: 2,
					},
				],
				slug: "crucible-of-storms",
				raidNumber: 2,
			},
			{
				raidNumber: 3,
				rankings: [
					{
						rank: 1,
						region: "us",
						id: 9484,
						regionRank: 29,
						realm: "Ragnaros",
						encountersDefeated: 8,
						name: "Unity",
					},
					{
						name: "Piezas",
						regionRank: 66,
						encountersDefeated: 8,
						id: 1036900,
						region: "us",
						rank: 2,
						realm: "Ragnaros",
					},
					{
						rank: 3,
						region: "us",
						realm: "Ragnaros",
						regionRank: 93,
						name: "Without Elders",
						encountersDefeated: 8,
						id: 655391,
					},
					{
						region: "us",
						name: "Epic Wipe",
						regionRank: 108,
						rank: 4,
						encountersDefeated: 8,
						realm: "Ragnaros",
						id: 42826,
					},
					{
						region: "us",
						name: "HTF",
						rank: 5,
						regionRank: 116,
						realm: "Ragnaros",
						encountersDefeated: 8,
						id: 42886,
					},
				],
				slug: "the-eternal-palace",
			},
			{
				rankings: [
					{
						region: "us",
						encountersDefeated: 8,
						id: 9484,
						rank: 1,
						regionRank: 25,
						name: "Unity",
						realm: "Ragnaros",
					},
					{
						region: "us",
						realm: "Azralon",
						rank: 2,
						name: "Overcoming",
						id: 9554,
						regionRank: 26,
						encountersDefeated: 8,
					},
					{
						realm: "Azralon",
						name: "Rise Above",
						encountersDefeated: 8,
						region: "us",
						rank: 3,
						regionRank: 71,
						id: 2394,
					},
					{
						encountersDefeated: 8,
						id: 481128,
						regionRank: 96,
						realm: "Ragnaros",
						name: "Erased Memories",
						region: "us",
						rank: 4,
					},
					{
						name: "Twisted Vortex",
						encountersDefeated: 8,
						regionRank: 111,
						id: 9174,
						realm: "Azralon",
						rank: 5,
						region: "us",
					},
				],
				slug: "uldir",
				raidNumber: 0,
			},
		],
	},
	raidBossesNames: {
		shadowlands: [],
		battleForAzeroth: [
			{
				bossList: [
					"taloc",
					"mother",
					"zekvoz-herald-of-nzoth",
					"vectis",
					"fetid-devourer",
					"zul-reborn",
					"mythrax-the-unraveler",
					"ghuun",
				],
				slug: "uldir",
				raidNumber: 0,
			},
			{
				bossList: [
					"champion-of-the-light",
					"grong",
					"jadefire-masters",
					"opulence",
					"conclave-of-the-chosen",
					"king-rastakhan",
					"high-tinker-mekkatorque",
					"stormwall-blockade",
					"lady-jaina-proudmoore",
				],
				slug: "battle-of-dazaralor",
				raidNumber: 1,
			},
			{
				raidNumber: 2,
				bossList: ["the-restless-cabal", "uunat-harbinger-of-the-void"],
				slug: "crucible-of-storms",
			},
			{
				slug: "the-eternal-palace",
				bossList: [
					"abyssal-commander-sivara",
					"radiance-of-azshara",
					"blackwater-behemoth",
					"lady-ashvane",
					"orgozoa",
					"the-queens-court",
					"zaqul",
					"queen-azshara",
				],
				raidNumber: 3,
			},
			{
				raidNumber: 4,
				bossList: [
					"wrathion-the-black-emperor",
					"the-prophet-skitra",
					"maut",
					"shadhar-the-insatiable",
					"the-hivemind",
					"dark-inquisitor-xanesh",
					"vexiona",
					"drestagath",
					"ra-den-the-despoiled",
					"ilgynoth-corruption-reborn",
					"carapace-of-nzoth",
					"nzoth-the-corruptor",
				],
				slug: "nyalotha-the-waking-city",
			},
		],
	},
};
